# Generated by Django 5.0.4 on 2025-02-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cocinero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('id_cocinero', models.ForeignKey(db_column='id_cocinero', on_delete=django.db.models.deletion.DO_NOTHING, to='cocinero.cocinero')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
