# Generated by Django 5.0.4 on 2025-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=300)),
                ('contraseña', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cocinero',
            },
        ),
    ]
